export const data = [
  {
    question: "What is the capital of France?",
    option1: "Paris",
    option2: "Rome",
    option3: "Madrid",
    option4: "Berlin",
    option5: "Lisbon",
    answer: 1,
  },
  {
    question: "Which of the following is a primary color?",
    option1: "Orange",
    option2: "Green",
    option3: "Red",
    option4: "Purple",
    option5: "Pink",
    answer: 3,
  },
  {
    question: "Which planet is known as the 'Red Planet'?",
    option1: "Neptune",
    option2: "Mars",
    option3: "Jupiter",
    option4: "Venus",
    option5: "Saturn",
    answer: 2,
  },
  {
    question: "What is 5 + 3?",
    option1: "7",
    option2: "8",
    option3: "6",
    option4: "10",
    option5: "9",
    answer: 2,
  },
  {
    question: "Which animal is known as the 'King of the Jungle'?",
    option1: "Leopard",
    option2: "Tiger",
    option3: "Lion",
    option4: "Gorilla",
    option5: "Elephant",
    answer: 3,
  },
];
